=encoding UTF-8

=head1 NAME

autolatex - Compilers des documents TeX

=head1 SYNOPSIS

autolatex [options] F<action> [F<action> ...]

=head1 DESCRIPTION

AutoLaTeX est un outil de compilation et de génération de documents LaTeX
de petites et grandes tailles. L'utilisateur peut facilement effectuer
toutes les étapes nécessaires pour générer un document PDF à partir d'un
fichier TeX: compilation d'une bibliographie, production du PDF, visualisation
du document. AutoLaTeX garde une trace des fichiers qui ont été modifiés
et connait les différents programmes qui sont nécessaires pour
produire la sortie (latex, bibtex, ...). Une des meilleures caractéristiques
de AutoLaTeX est de fournir des règles de traduction (translators) qui
permettent de générer automatiquement les figures PNG ou PDF inclues dans le
TeX. Cette génération est effectuée à partir de fichiers dans différents
formats (svg, fig, dia, asta, ...).

Par exemple, envisager un projet qui a un seul fichier LaTeX F<mydoc.tex>
comme entrée. Sans AutoLaTeX, pour produire un fichier F<.pdf>, vous devez
utiliser la séquence de commandes qui suit :

     F<pdflatex mydoc.tex>
     F<bibtex mydoc.tex>
     F<pdflatex mydoc.tex>
     F<pdflatex mydoc.tex>
     F<pdflatex mydoc.tex>
     
La triple invocation de LaTeX permet de s'assurer que toutes les
références ont été correctement résolues et que tous les changements
de la mise en page dus à l'insertion des références ont été comptabilisés.
Cette séquence de commandes n'est pas horrible, mais il s'agit toujours 
de plusieurs commandes à entrer. Pour utiliser AutoLaTeX pour ce projet,
vous pouvez utiliser une des méthodes suivantes sur la ligne de commande:

     F<autolatex -f mydoc.tex>
     F<autolatex>
  
Pour les documents pour lesquels vous auriez besoin d'exécuter des
programmes externes pour créer les versions PDF des figures, ou pour
lesquels vous voulez exécuter BibTeX/Biber pour générer les bibliographies,
la génération des fichiers <.pdf> (ou autres) devient de plus en plus
compliquée à traiter manuellement. Avec AutoLaTeX, ces opérations sont
toujours très simples: vous n'avez rien à faire. AutoLaTeX appelle pour
vous les convertisseurs de figures et les autres programmes. Chaque
convertisseur est capable de convertir un fichier source de l'image (eps,
svg, Gnuplot, ...) dans un PDF ou un fichier PNG.
   
Espérons que cette introduction a fourni un exemple adéquat
concernant la façon dont AutoLaTeX peut simplifier la gestion des
documents LaTeX. Le système AutoLaTeX est assez simple
pour les petits documents et assez puissant pour les grands
documents. Le reste de ce manuel vous fournira une documentation
complète sur l'utilisation de AutoLaTeX ainsi que sur sa 
configuration et les instructions d'installation.

AutoLaTeX fournit plusieurs interfaces graphiques.
Voir la section ci-dessous pour plus de détails.

=head1 ACTIONS

AutoLaTeX fournit un ensemble fixe d'actions, les arguments à
passer à AutoLaTeX pour exécuter un de ses modules, pour tous
les projets. L'action par défaut est B<all>.

Si l'action spécifiée n'est pas reconnue par AutoLateX, un programme nommé C<autolatex-action> (avec
C<action> remplacé par la chaîne de caractères du nom de l'action) est recherché sur votre système,
et lancé.
Par exemple, C<autolatex config> permet de lancer l'interface graphique de configuration de AutoLaTeX.
Cette interface est supportée par le programme C<autolatex-config>, fourni dans la distribution AutoLaTeX.

Les actions fournies par AutoLaTeX sont :

=over 4

=item B<all>

Identique à B<view>, à l'exception que le visualisateur est lancé
uniquement si la configuration ou l'option CLI l'indique.

=item B<biblio>

Exécute toutes les tâches pour générer la bibliographie (bibtex,
biber, ...)

=item B<clean>

Nettoie le répertoire de travail courant en supprimant tous les
fichiers temporaires générés par LaTeX et les outils associés.

=item B<cleanall>

Similaire à B<clean>. En plus, les fichiers backups (~, .bak) sont supprimés.
Les figures générées par les convertisseurs sont également supprimées.

=item B<commit>

Envoyer les changements à un gestion de source (CVS, SVN, GIT).

=item B<gen_doc>

Production du fichier .pdf/.dvi/.ps associé au document.

=item B<images>

Génération automatique des figures avec les convertisseurs.

=item B<makeflat>

Créer une version du document, dans le sous-répertoire
'flat_version', dans laquelle il ya un seul fichier TeX, et où
tous les autres fichiers se trouvent dans le même répertoire que
le fichier TeX (images, ...).
Cette action est utile pour créer une version du document qui
peut être téléchargée directement sur ​​les sites en-ligne de
publication scientifique (comme Elsevier). Cette action, 
lorsqu'elle est utilisée avec l'option F<--biblio>, permet
de choisir si la bibliographie sera laissée dans un fichier
BibTeX ou sera placée directement à l'intérieur du fichier TeX.
Cette dernière est l'option par défaut.

Si vous ne voulez pas de la version "plate" soit créée dans un
sous-répertoire nommé 'flat_version', bous pouvez donner
le chemin du répertoire dans lequel écrire la version "plate",
ou donner le nom de base du répertoire dans lequel écrire.

Pour changer le chemin du répertoire de sortie de la version
"plate", vous devez utiliser l'option en ligne de commande
suivante :

F<--set makeflat.output=>I<chemin>

Pour changer le nom de base du répertoire de sortie de la version
"plate", vous devez utiliser l'option en ligne de commande
suivante :

F<--set makeflat.basename=>I<nom>

=item B<makeindex>

Lancement de l'outils de création d'un index : MakeIndex.

=item B<showimages>

Affiche une liste des images détectées par AutoLaTeX.

=item B<showimagemap>

Affiche une liste des images détectées par AutoLaTeX, avec les noms
des convertisseurs utilisés.

=item B<showpath>

Affiche la variable d'environnement PATH.

=item B<update>

Execution d'un 'update' dans votre système de gestion de code source
(CVS, SVN, GIT).

=item B<view>

Similaire à B<gen_doc>. En plus, lance le visualisateur.

=back

=head1 OPTIONS

=over 4

=item B<--[no]auto>

Activer ou désactiver la génération automatique des figures.

=item B<--[no]asyncview>

Activer ou désactiver le lancement asynchrone du visualisateur.
Si le visualisateur est lancé de manière asynchone, AutoLaTeX
n'attend pas l'arrêt du visualisateur avant d'arrêter son exécution.
Si le visualisateur est lancé de manière synchrone, AutoLaTeX attend
le visualisateur pour arrêter son exécution.

=item B<--[no]biblio>

Activer ou désactiver l'appel à l'outil de création de bibliographie
(BibTeX, Biber, ...)

=item B<--continuous[=temps_attente]>

=item B<--nocontinuous>

Cette option permet de ne pas arrêter AutoLaTeX et de continuellement réaliser
les actions passées en paramètres.
Cette option provique une boucle infinie dans AutoLaTeX. Elle possède un effet
similaire au script suivant (en bash) :
 while 1
 do
   autolatex "$@"
   sleep B<temps_attente>
 done

La valeur B<temps_attente> permet d'ajouter un temps d'attente 
entre deux boucles de AutoLaTeX. Si elle n'est pas fournie, 0 est utilisé.
L'option B<--continuous> force l'utilisation de l'option B<--asyncview>.

Si vous posséder un bon visualisateur, l'affichage du document dans
ce dernier sera automatiquement mis-à-jour (avec certaines versions
de UNIX/Linux "gv -watch" réalise ce raffraichissement automatique
pour des fichiers Postscript
With a good viewer the display will be automatically updated.
(Under some but not all versions of UNIX/Linux "gv -watch"  does
this  for  postscript  files). De nombreux autres visualisateurs
nécessitent une mise-à-jour manuelle.

Note importante : le logiciel acroread sous MS-Windows pose un verrou
sur le fichier PDF, et n'autorise pas les nouvelles versions du PDF 
d'être écrites. Par conséquent, ce n'est pas une bonne idée d'utiliser
acroread pour visualiser les fichiers PDF en mode continu.

=item B<--createconfig[=S<type>]>

Ne pas compiler le document LaTeX, mais de créer un fichier de configuration.
Le fichier de configuration créé dépend de la valeur S<type>. Si le S<type>
est égal à S<projet>, AutoLaTeX créer la configuration dans le dossier
consacré au document LaTeX. Otherwhise il va créer le fichier de
configuration dans le répertoire personnel de l'utilisateur.
Le fichier de configuration du projet est
F<path/to/project/.autolatex_project.cfg> sur les plate-formes Unix, et
F<path\to\project\autolatex_project.cfg> sur d'autres plateformes.
Le fichier de configuration au niveau utilisateur est
F<$HOME/.autolatex> sur Unix,
<C:\Documents and Settings\User\Local Settings\Application Data\autolatex.conf>
sur les plateformes Windows et F<$HOME/autolatex.conf> sur d'autres plateformes.

=item B<--createist>

Créer un fichier de style MakeIndex dans le répertoire du
document LaTeX. Le fichier créé sera nommé 'default.ist'.
Si un fichier portant ce nom existe déjà, il sera écrasé.

=item B<--debug>

Execute AutoLaTeX en mode Debug. Le niveau de verbiage est à 5, et
tous les warnings générés par le code Perl sont considérés comme
des erreurs.

=item B<--defaultist>

Autorise AutoLaTeX à utiliser le fichier de style MakeIndex
par défaut. Ce fichier est fourni par AutoLaTeX.

Les options --index et --noindex permettent également de
changer le comportement de AutoLaTeX concernant MakeIndex.

=item B<--dvi>

Génération d'un fichier DVI ou XDVI à la place d'un fichier PDF.

=item B<--exclude=S<nom>>

Interdit à AutoLaTeX de charger le convertisseur nommé S<nom>.
Voir ci-dessous pour une liste des convertisseurs disponibles.

L'option --include permet d'autoriser un convertisseur; et
l'option -I permet de donner un répertoire dans lesquel les
convertisseurs pourront être découverts.

=item B<-f=F<fichier>>

=item B<--file=F<fichier>>

Spécification du fichier LaTeX principal. Si cette option
n'est pas spécifiéé, AutoLaTeX recherche un fichier TeX
dans le répertoire courant.

=item B<--file-line-warning>

Active our désactive le format étendu des avertissements.
Ce format ajoute le nom de fichier et le numéro de ligne 
d'un avertissement, juste avant le message lui-même.

=item B<--fixconfig[=F<fichier>]>

Corriger la syntaxe d'un fichier de configuration. Si le F<fichier>
n'est pas spécifié sur la ligne de commande, AutoLaTeX essayer de
corriger la configuration du document, ou la configuration de
l'utilisateur si aucun fichier de configuration du document n'était
trouvé.

=item B<-?>

=item B<--help>

Affiche ce manuel.

=item B<-I=S<chemins>>

Informe AutoLaTeX qu'il pourrait trouver des convertisseurs
dans les répertoires spécifiés. Les S<chemins> donnés
forment une liste de chemins séparés par le caractère séparateur
de votre système d'exploitation (':' sur Unix, ';' pour Windows
par exemple).

L'option --exclude permet d'interdire des convertisseurs;
et l'option --include permet d'autoriser des convertisseurs.

=item B<--imgdirectory=S<répertoires>>

Spécification de répertoires dans lesquels AutoLaTeX pourra rechercher
des figures à convertir.
Chaque fois que cette option est mise sur la ligne de commande, un
répertoire est ajouté dans la liste des répertoires
à explorer.

=item B<--include=S<nom>>

Autorise AutoLaTeX de charger le convertisseur nommé S<nom>.
Voir ci-dessous pour une liste des convertisseurs disponibles.

L'option --exclude permet d'interdir un convertisseur; et
l'option -I permet de donner un répertoire dans lesquel les
convertisseurs pourront être découverts.

=item B<--index[=F<fichier_style>]>

Autorise l'utilisation de MakeIndex.

Si cette option est donnée avec une valeur, cette valeur
est considérée comme le chemin d'un fichier de style MakeIndex
(.ist).

Si cette option est utilisée sans valeur, AutoLaTeX utilisera
MakeIndex et tentera de détecter le fichier de style
présent dans le répertoire du document.
Si ce fichier de style n'existe pas, AutoLaTeX ne donnera
pas de style à MakeIndex.

Les options --defaultist et --noindex permettent également
de changer le comportement de AutoLaTeX concernant MakeIndex.

=item B<--latex>

Utilise le compilateur LaTeX historique : F<latex>.

=item B<--lualatex>

Utilise le compilateur LaTeX : F<lualatex>.

=item B<--noindex>

Interdit l'utilisation de MakeIndex.

Les options --defaultist et --index permettent également
de changer le comportement de AutoLaTeX concernant MakeIndex.


=item B<--pdf>

AutoLaTeX produit un fichier PDF.

=item B<--pdflatex>

Utilise le compilateur LaTeX : F<pdflatex>.

=item B<--progress[=n]>

Activer ou désactiver l'affichage de la progression des tâches.
La valeur passée à ce paramètre permet de déterminer quel
caractère sera affiché à la fin de chaque ligne.
Par défaut, le caractère retour-chariot C<\r> est utilisé.
Si vous spécifiez une valeur égale à "C<n>", le caractère
saut-à-ligne C<\n> sera utilisé.

=item B<--ps>

AutoLaTeX produit un fichier Postscript à la place d'un fichier PDF.

=item B<-q>

=item B<--quiet>

AutoLaTeX ne doit pas être verbeux (voir B<-v> pour rendre
l'outil verbeux).

=item B<--search-project-from=F<fichier>>

Lorsque cette option est donnée, AutoLaTex recherche un fichier
de configuration projet (habituellement F<.autolatex_project.cfg>
sur une plate-forme Unix) dans le dossier du F<fichier> spécifié
ou dans l'un de ses dossiers parent. Lorsqu'un fichier de
configuration a été trouvé, AutoLaTeX considère que le dossier
dans lequel la construction doit avoir lieu est le dossier
où est placé le fichier de configuration trouvé.

=item B<--set [S<convertisseur>.]S<nom>=S<valeur>>

Affecte la S<valeur> à une variable interne ayant un S<nom>
Les valeurs internes sont limitées et correspond aux directives
"set" de la syntaxe du fichier de configuration.

Si un S<convertisseur> est donnée, c'est le nom du convertisseur
pour lequel la valeur doit être initialisée. Si aucun
S<convertisseur> est donné, "generation' est utilisé comme préfixe
par défaut.

=item B<--stderr>

Préfère afficher les messages sur la sortie standard d'erreur.

=item B<--stdout>

Préfère afficher les messages sur la sortie standard.

=item B<--[no]synctex>

Activer ou désactiver la génération du fichier de sortie avec SyncTeX.
SyncTeX est un mécanisme qui permet de lié un visualisateur et un
éditeur TeX. Quand vous cliquez dans l'un, l'autre logiciel met en
surbrillance la ligne correspondante de son côté.

=item B<-v>

Chaque fois que cette option est donnée, AutoLaTeX est plus
verbeux. Notez que 1) si vous mettez 5 fois l'option B<-v>
sur la ligne de commande, AutoLaTeX considérera
les avertissements de Perl comme des erreurs, 2) si vous mettez
6 fois l'option B<-v> sur la ligne de commande, AutoLaTeX est
arrêter immédiatement et affiche la configuration courante.

=item B<--version>

Affiche la version de AutoLaTeX.

=item B<--view[=F<fichier>]>

=item B<--noview>

Autorise ou interdit le lancement d'un visualisateur à la fin du
processus de génération du document. La ligne de commande permettant
de lancer le visualisateur peut être spécifiée par F<fichier>.
Si cette valeur n'est pas donnée, AutoLaTeX essyera de lancer
les outils F<acroread>, F<kpdf>, F<evince>, F<gv>, et F<xpdf>.

=item B<-W>

=item B<--Wall>

=item B<--Wnone>

Sélectionne les avertissements qui seront affichés : B<--Wall> pour tous,
B<--Wnone> pour aucun, et B<-W> pour augmenter le niveau d'avertissement.
B<-W> est la configuration par défaut utilisée par AutoLaTeX.

=item B<--xelatex>

Utilise le compilateur LaTeX : F<xelatex>.

=back

=head1 AUTO GENERATION DES FIGURES

Un convertisseur est utilisé pour transformer une figure depuis
un format source dans le format cible (PDF ou EPS) supporté par
LaTeX. Ce convertisseur est un programme externe (par exemple
epstopdf) ou un script Perl interne.

Chaque convertisseur supporté est décrit dans un
fichier '.transdef'. Ce fichier contient la définition des
de la ligne de commande shell pour lancer le convertisseur, ou
le code Perl à utiliser pour réaliser la convertion. Pour créer
un nouveau traducteur, nous vous recommandons de copier/coller
un fichier '.transdef' existant et de modifier son contenu.
Même si vous avez exclu un convertisseur avec la ligne de
commande, il est automatiquement inclus par AutoLaTeX quand
il est invoqué par un traducteur inclus.

Les convertisseurs fournis avec AutoLaTeX sont :

=over 

=item B<Astah/Jude (asta) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              astah2pdf

=item Convertisseur externe utilisé :    astah-uml, astah-pro

=item Convertisseur utilisé :            svg2pdf

=item Format d'entrée :                  .asta .jude .juth

=item Format de sortie :                 .pdf

=back

=item B<Astah/Jude (asta) vers Portable Network Graphic (png)>

=over 12

=item Nom :                              astah2png

=item Convertisseur externe utilisé :    astah-com, astah-uml, astah-pro

=item Convertisseur utilisé :

=item Format d'entrée :                  .asta .jude .juth

=item Format de sortie :                 .png

=back

=item B<Asymptote (asy) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              asy2pdf

=item Convertisseur externe utilisé :    asy

=item Use translator:                    eps2pdf

=item Format d'entrée :                  .asy

=item Format de sortie :                 .pdf

=back

=item B<Code source C/C++ (.cpp, .c, .hpp, .h) vers code source TeX (tex): variante TeXify>

=over 12

=item Nom :                              cpp2tex_texify

=item Convertisseur externe utilisé :    texifyc++

=item Convertisseur utilisé :

=item Format d'entrée :                  .cpp, .c, .hpp, .h, .c++, .h++

=item Format de sortie :                 .tex

=back

=item B<Bitmap compresée vers bitmap non compressée>

basé sur l'outil L<zcat>. Ce convertisseur suppose que des fichiers
d'entrée compressés (zippés). L'extension des fichiers d'entrée est
'.gz'. Ce convertisseur permet de stocker des données compressées
comme matière première pour le compilateur latex. Les bitmaps sont
décompressés dans un fichier portant le même nom que la source, à
l'exception de l'extension  '.gz' supprimée du nom.

=over 12

=item Nom :                              imggz2img

=item Convertisseur externe utilisé :    zcat

=item Convertisseur utilisé :           

=item Format d'entrée :                  XXX.gz

=item Format de sortie :                 XXX

=back

=item B<Diagram Editor (dia) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              dia2pdf

=item Convertisseur externe utilisé :    dia

=item Convertisseur utilisé :            eps2pdf

=item Format d'entrée :                  .dia

=item Format de sortie :                 .pdf

=back

=item B<Diagram Editor (dia) vers TeX dans du Portable Document Format (pdf+tex)>

PDF part:

=over 12

=item Nom :                              dia2pdf+tex

=item Convertisseur externe utilisé :    dia

=item Convertisseur utilisé :

=item Format d'entrée :                  .dia_tex .diat .dia+tex .diatex .tex.dia +tex.dia

=item Format de sortie :                 .pdf

=back

TeX part:

=over 12

=item Nom :                              dia2pdf+tex

=item Convertisseur externe utilisé :    dia

=item Convertisseur utilisé :           

=item Format d'entrée :                  .dia_tex .diat .dia+tex .diatex .tex.dia +tex.dia

=item Format de sortie :                 .pdftex_t

=back

=item B<Dot Graphviz (dot) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              dot2pdf

=item Convertisseur externe utilisé :    dot

=item Convertisseur utilisé :

=item Format d'entrée :                  .dot

=item Format de sortie :                 .pdf

=back

=item B<Dot Graphviz (dot) vers Portable Network Graphic (png)>

=over 12

=item Nom :                              dot2png

=item Convertisseur externe utilisé :    dot

=item Convertisseur utilisé :

=item Format d'entrée :                  .dot

=item Format de sortie :                 .png

=back

=item B<Dot Graphviz (dot) vers TeX (tex)>

=over 12

=item Nom :                              dot2tex

=item Convertisseur externe utilisé :    dot

=item Convertisseur utilisé :

=item Format d'entrée :                  .dot

=item Format de sortie :                 .tex

=back

=item B<Encapsuled PostScript (eps) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              eps2pdf_epstopdf

=item Convertisseur externe utilisé :    epstopdf

=item Convertisseur utilisé :

=item Format d'entrée :                  .eps

=item Format de sortie :                 .pdf

=back

=item B<Encapsuled PostScript (eps) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              eps2pdf_ps2pdf

=item Convertisseur externe utilisé :    ps2pdf

=item Convertisseur utilisé :

=item Format d'entrée :                  .eps

=item Format de sortie :                 .pdf

=back

=item B<XFig document (fig) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              fig2pdf

=item Convertisseur externe utilisé :    fig2dev

=item Convertisseur utilisé :           

=item Format d'entrée :                  .fig

=item Format de sortie :                 .pdf

=back

=item B<XFig document (fig) vers TeX dans du Portable Document Format (pdf+tex)>

PDF part:

=over 12

=item Nom :                              fig2pdf+tex

=item Convertisseur externe utilisé :    fig2dev

=item Convertisseur utilisé :

=item Format d'entrée :                  .figt .fig_tex .figtex .fig+tex .tex.fig +tex.fig

=item Format de sortie :                 .pdf

=back

TeX part:

=over 12

=item Nom :                              fig2pdf+tex

=item Convertisseur externe utilisé :    fig2dev

=item Convertisseur utilisé :           

=item Format d'entrée :                  .figt .fig_tex .figtex .fig+tex .tex.fig +tex.fig

=item Format de sortie :                 .pdftex_t

=back

=item B<Geogebra (ggb) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              ggb2pdf

=item Convertisseur externe utilisé :    geogebra

=item Use translator:                    

=item Format d'entrée :                  .ggb

=item Format de sortie :                 .pdf

=back

=item B<Graph Layout Engine (gle) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              gle2pdf

=item Convertisseur externe utilisé :    gle

=item Use translator:                    

=item Format d'entrée :                  .gle

=item Format de sortie :                 .pdf

=back

=item B<Graph Layout Engine (gle) vers Portable Network Graphic (png)>

=over 12

=item Nom :                              gle2png

=item Convertisseur externe utilisé :    gle

=item Convertisseur utilisé :            

=item Format d'entrée :                  .gle

=item Format de sortie :                 .png

=back

=item B<Graph eXchange Language (gxl) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              gxl2pdf

=item Convertisseur externe utilisé :    gxl2dot

=item Convertisseur utilisé :            dot2pdf

=item Format d'entrée :                  .gxl

=item Format de sortie :                 .pdf

=back

=item B<Graph eXchange Language (gxl) vers Portable Network Graphic (png)>

=over 12

=item Nom :                              gxl2png

=item Convertisseur externe utilisé :    gxl2dot

=item Convertisseur utilisé :            dot2png

=item Format d'entrée :                  .gxl

=item Format de sortie :                 .png

=back

=item B<Code source Java (java) vers code source TeX (tex): variante TeXify>

=over 12

=item Nom :                              java2tex_texify

=item Convertisseur externe utilisé :    texifyjava

=item Convertisseur utilisé :

=item Format d'entrée :                  .java

=item Format de sortie :                 .tex

=back

=item B<Script Lisp (lisp) vers code source TeX (tex): variante TeXify>

=over 12

=item Nom :                              lisp2tex_texify

=item Convertisseur externe utilisé :    texifylisp

=item Convertisseur utilisé :

=item Format d'entrée :                  .lisp

=item Format de sortie :                 .tex

=back

=item B<Script MatLab (m) vers code source TeX (tex): variante TeXify>

=over 12

=item Nom :                              matlab2tex_texify

=item Convertisseur externe utilisé :    texifymatlab

=item Convertisseur utilisé :

=item Format d'entrée :                  .m

=item Format de sortie :                 .tex

=back

=item B<Script ML (ml) vers code source TeX (tex): variante TeXify>

=over 12

=item Nom :                              ml2tex_texify

=item Convertisseur externe utilisé :    texifyml

=item Convertisseur utilisé :

=item Format d'entrée :                  .ml

=item Format de sortie :                 .tex

=back

=item B<Script Perl (perl) vers code source TeX (tex): variante TeXify>

=over 12

=item Nom :                              perl2tex_texify

=item Convertisseur externe utilisé :    texifyperl

=item Convertisseur utilisé :

=item Format d'entrée :                  .perl .pl

=item Format de sortie :                 .tex

=back

=item B<Gnuplot (plot) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              plot2pdf

=item Convertisseur externe utilisé :    gnuplot

=item Convertisseur utilisé :            eps2pdf

=item Format d'entrée :                  .plot .gnu

=item Format de sortie :                 .pdf

=back

=item B<Gnuplot (plot) vers TeX dans du Portable Document Format (pdf+tex)>

PDF part:

=over 12

=item Nom :                              plot2pdf+tex

=item Convertisseur externe utilisé :    gnuplot

=item Convertisseur utilisé :            eps2pdf

=item Format d'entrée :                  .plott .plot_tex .plottex .plot+tex .tex.plot +tex.plot .gnut .gnu_tex .gnutex .gnu+tex .tex.gnu +tex.gnu

=item Format de sortie :                 .pdf

=back

TeX part:

=over 12

=item Nom :                              plot2pdf+tex

=item Convertisseur externe utilisé :    gnuplot

=item Convertisseur utilisé :            

=item Format d'entrée :                  .plott .plot_tex .plottex .plot+tex .tex.plot +tex.plot .gnut .gnu_tex .gnutex .gnu+tex .tex.gnu +tex.gnu

=item Format de sortie :                 .pdftex_t

=back

=item B<Code source Python (py) vers code source TeX (tex): variante TeXify>

=over 12

=item Nom :                              python2tex_texify

=item Convertisseur externe utilisé :    texifypython

=item Convertisseur utilisé :

=item Format d'entrée :                  .py

=item Format de sortie :                 .tex

=back

=item B<Code source Ruby (rb) vers code source TeX (tex): variante TeXify>

=over 12

=item Nom :                              ruby2tex_texify

=item Convertisseur externe utilisé :    texifyruby

=item Convertisseur utilisé :

=item Format d'entrée :                  .rb

=item Format de sortie :                 .tex

=back

=item B<Script SQL (sql) vers code source TeX (tex): variante TeXify>

=over 12

=item Nom :                              sql2tex_texify

=item Convertisseur externe utilisé :    texifysql

=item Convertisseur utilisé :

=item Format d'entrée :                  .sql

=item Format de sortie :                 .tex

=back

=item B<Scalable Vector Graphic (svg) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              svg2pdf

=item Convertisseur externe utilisé :    inkscape

=item Convertisseur utilisé :            eps2pdf

=item Format d'entrée :                  .svg

=item Format de sortie :                 .pdf

=back

=item B<Scalable Vector Graphic (svg) vers TeX dans du Portable Document Format (pdf+tex)>

PDF part:

=over 12

=item Nom :                              svg2pdf+tex

=item Convertisseur externe utilisé :    inkscape

=item Convertisseur utilisé :            eps2pdf

=item Format d'entrée :                  .svgt .svg_t .svgtex .svg+tex .tex.svg +tex.svg

=item Format de sortie :                 .pdf

=back

TeX part:

=over 12

=item Nom :                              svg2pdf+tex

=item Convertisseur externe utilisé :    inkscape

=item Convertisseur utilisé :           

=item Format d'entrée :                  .svgt .svg_t .svgtex .svg+tex .tex.svg +tex.svg

=item Format de sortie :                 .pdftex_t

=back

=item B<Scalable Vector Graphic (svg) vers Portable Network Graphic (png)>

=over 12

=item Nom :                              svg2png

=item Convertisseur externe utilisé :    inkscape

=item Convertisseur utilisé :           

=item Format d'entrée :                  .svg

=item Format de sortie :                 .png

=back

=item B<Scalable Vector Graphic avec calques (svg) vers Calques Beamer>

=over 12

=item Nom :                              svg2pdf+layers

=item Convertisseur externe utilisé :    inkscape

=item Convertisseur utilisé :            

=item Format d'entrée :                  .svgl .svg_l .svglayers .svg+layers .layers.svg +layers.svg

=item Format de sortie :                 .pdftex_t .pdf

=back

=item B<Scalable Vector Graphic avec calques (svg) vers TeX dans des calques Beamer>

PDF part:

=over 12

=item Nom :                              svg2pdf+layers+tex

=item Convertisseur externe utilisé :    inkscape

=item Convertisseur utilisé :            eps2pdf

=item Format d'entrée :                  .svglt .svg_lt .svglayerstex .svgtexlayers .svg+layers+tex .svg+tex+layers .layers.tex.svg .tex.layers.svg +layers+tex.svg +tex+layers.svg

=item Format de sortie :                 .pdf

=back

TeX part:

=over 12

=item Nom :                              svg2pdf+layers+tex

=item Convertisseur externe utilisé :    inkscape

=item Convertisseur utilisé :           

=item Format d'entrée :                  .svglt .svg_lt .svglayerstex .svgtexlayers .svg+layers+tex .svg+tex+layers .layers.tex.svg .tex.layers.svg +layers+tex.svg +tex+layers.svg

=item Format de sortie :                 .pdftex_t

=back

=item B<Gimp (xcf) vers Portable Document Format (pdf)>

=over 12

=item Nom :                              xcf2pdf

=item Convertisseur externe utilisé :    convert

=item Convertisseur utilisé :            

=item Format d'entrée :                  .xcf

=item Format de sortie :                 .pdf

=back

=item B<Gimp (xcf) vers Portable Network Graphic (png)>

=over 12

=item Nom :                              xcf2pdf

=item Convertisseur externe utilisé :    convert

=item Convertisseur utilisé :            

=item Format d'entrée :                  .xcf

=item Format de sortie :                 .png

=back

=item B<UML Metadata Interchange (xmi) vers Portable Document Format (pdf): variante Umbrello>

=over 12

=item Nom :                              xmi2pdf_umbrello

=item Convertisseur externe utilisé :    umbrello

=item Convertisseur utilisé :            eps2pdf

=item Format d'entrée :                  .xmi

=item Format de sortie :                 .pdf

=back

=item B<UML Metadata Interchange (xmi) versPortable Document Format (pdf): variante uml2svg>

=over 12

=item Nom :                              xmi2pdf_uml2svg

=item Convertisseur externe utilisé :    uml2svg

=item Convertisseur utilisé :            svg2pdf

=item Format d'entrée :                  .xmi

=item Format de sortie :                 .pdf

=back

=item B<UML Metadata Interchange (xmi) vers Portable Document Format (pdf): variante xmi2svg>

=over 12

=item Nom :                              xmi2pdf_xmi2svg

=item Convertisseur externe utilisé :    xmi2svg

=item Convertisseur utilisé :            svg2pdf

=item Format d'entrée :                  .xmi

=item Format de sortie :                 .pdf

=back

=item B<Visio Binary Draw (vsd) vers Portable Document Format (pdf)>

=over 12

=item Name:                              vsd2pdf

=item Use external converter:            inkscape

=item Use translator:                    

=item Input format:                      .vsd .vdx .vsdx

=item Output format:                     .pdf

=back

=back

=head1 PAQUET LATEX

AutoLaTeX fournit un style LaTeX nommé F<autolatex.sty>. Il fournit les fonctions suivantes :

=over 4

=item B<\includegraphicswtex[options]{fichier}>

inclusion d'une figure incluant/combinée avec des macros TeX. Le fichier doit avoir l'une des extensions suivantes : F<.pdftex_t>, F<.pdftex_t>, F<.pstex_t>, F<.pdf_tex>, F<.ps_tex>. Les B<options> doit être l'une de : F<width=XX>, ou F<height=XX>; où F<XX> est une taille.

=item B<\includefigurewtex[options]{fichier}>

Identique à B<\includegraphicswtex>.

=item B<\includeanimatedfigure[options]{fichier}>

inclusion des calques d'une figure dans une présentation Beamer. La partie graphique de
chaque calque est dans un fichier PDF spécifique. La figure est un fihier TeX qui
inclue les différents fichiers PDF dans un environnement compatible avec Beamer.
 Le fichier doit avoir l'une des extensions suivantes : F<.pdftex_t>, F<.pdftex_t>, F<.pstex_t>, F<.pdf_tex>, F<.ps_tex>. Les B<options> doit être l'une de : F<width=XX>, ou F<height=XX>; où F<XX> est une taille.

Par défaut, un remplace remplace le calque précédent quand il est affiché. Vous pouvez changer
la spécification de recouvrement en ajoutant la chaîne F<"spec"> dans le titre du calque dans
votre éditeur SVG, par exemple. La partie F<spec> est la spécification des numéros de diapositives
sur lesquels le calque doit apparaître dans Beamer. Par exemple, F<2> signifie 'uniquement sur
​​la diapositive 2'; F<6-> signifie 'de la diapositive 6 à la fin'.

=item B<\includeanimatedfigurewtex[options]{fichier}>

inclusion des calques d'une figure dans une présentation Beamer combinés avec des macros TeX.
La partie graphique de chaque calque est dans un fichier PDF spécifique. La figure est un fihier TeX qui
inclue les différents fichiers PDF dans un environnement compatible avec Beamer.
 Le fichier doit avoir l'une des extensions suivantes : F<.pdftex_t>, F<.pdftex_t>, F<.pstex_t>, F<.pdf_tex>, F<.ps_tex>. Les B<options> doit être l'une de : F<width=XX>, ou F<height=XX>; où F<XX> est une taille.

Par défaut, un remplace remplace le calque précédent quand il est affiché. Vous pouvez changer
la spécification de recouvrement en ajoutant la chaîne F<"spec"> dans le titre du calque dans
votre éditeur SVG, par exemple. La partie F<spec> est la spécification des numéros de diapositives
sur lesquels le calque doit apparaître dans Beamer. Par exemple, F<2> signifie 'uniquement sur
​​la diapositive 2'; F<6-> signifie 'de la diapositive 6 à la fin'.

=item B<\DeclareGraphicsExtensionsWtex{extensions}>

permet de définir les extensions des fichiers qui sont considérées par B<\includegraphicswtex>
pour trouver les fichiers des figures.

=item B<\graphicspath{{chemin1},{chemin2}...}>

est une macro fournie par le paquet 'graphicx.sty'. Elle permet de définir les chemins de recherche
des figures.

=back

=head1 FICHIER DE CONFIGURATION

=head2 Emplacement des fichiers de configuration

Les fichiers de configuration utilisés par AutoLaTeX peuvent être à un plusieurs endroits :

=over 4

=item * Configuration système (pour tous les utilisateurs) : dans le répertoire où a été installé AutoLaTeX (généralement /usr/lib/autolatex/ ou /etc/autolatex/ sur les systèmes Unix).

=item * Configuration utilisateur : deux cas: le répertoire de configuration nommé S<$HOME/.autolatex> sur Unix, ou S<C:\Documents and Settings\E<lt>userE<gt>\Local Settings\Application Data\autolatex> sur Windows existe, ou non.

Dans le premier cas, le fichier de configuration est stocké dans le répertoire et est nommé S <autolatex.conf>.

Dans le second cas, le fichier de configuration se trouve dans le répertoire de l'utilisateur et est nommé S<$HOME/.autolatex> sur Unix, et S<C:\Documents and Settings\E<lt>userE<gt>\Local Settings\Application Data\autolatex.conf> sur Windows.

=item * Configuration projet/document: le fichier de configuration dans le même répertoire que le fichier principal TeX du projet. Il est nommé S<.autolatex_project.cfg> sous Unix et S<autolatex_project.cfg> sur Windows.

=back

=head2 Syntaxe des fichiers de configuration

Les fichiers de configuration respectent une syntaxe similaire aux fichiers '.ini' de Windows.

Un commentaire commence par le caractère '#' ou ';' et il se termine à la fin de la ligne.

Chaque directive de configuration doit être à l'intérieur d'une section de configuration. Une section de configuration
est déclarée par son nom entre crochets. Exemple: F<[mysection]>

Chaque directive doit être déclarée comme suit: F<nom directive = value>

Plusieurs noms de section sont réservés par AutoLaTeX, les autres sont supposés être la configuration pour les traducteurs.

=head3 Section [Viewer]

Cette section décrit la configuration du visualisateur.
Les directives reconnues sont :

=over 4

=item I<view> : activer ou désactiver le lancement du visualisateur. Valeurs acceptées: F<yes> or F<no>.
	
=item I<viewer> : ligne de commande pour lancer le visualisateur. Valeurs acceptées : toute ligne de commande.

=back

=head3 Section [Generation]

Cette section permet de configurer le processus de génération de AutoLaTeX. process used by AutoLaTeX.
Les directives reconnues sont :

=over 4

=item I<main file> : spécification du nom simple (le 'basename', le nom de fichier sans les noms de répertoire) du fichier principal TeX à compiler. Cette option n'est autorisée que dans le fichier de configuration du projet.

=item I<generate images> : activer ou désactiver la génération automatique des figures. Valeurs acceptées : F<yes> or F<no>

=item I<image directory> : Spécifier des répertoires à l'intérieur desquels AutoLaTeX va rechercher les figures qui doivent être traités par les convertisseurs. Les différents chemins sont séparés par le caractère séparateur de chemin (F<':'> sur Unix, F<';'> sur Windows).

=item I<generation type> : indique le type du document généré. Valeurs acceptées :

=over 8

=item F<pdf> - génération d'un document PDF

=item F<dvi> - génération d'un document DVI ou XDVI

=item F<ps> - génération d'un document PostScript

=back

=item I<tex compiler> : indique le compilateur TeX à utiliser. Valeurs acceptées :

=over 8

=item F<latex> - utilise F<latex>

=item F<pdflatex> - utilise F<pdflatex>

=item F<xelatex> - utilise F<xelatex>

=item F<lualatex> - utilise F<lualatex>

=back

=item I<synctex> : indique si le document généré doit être produit en utilisant SyncTeX, ou non.

=item I<makeindex style> : spécification du style d'index utilisé par MakeIndex. La valeur de cette directive est une liste de valeurs séparées par des virgules, dans l'ordre de préférence. Les différentes valeurs supportées sont :

=over 8

=item F<E<lt>fichierE<gt>> - si un nom de fichier est donné, AutoLaTeX considère qu'il s'agit du fichier .ist à utiliser;

=item F<@system> - AutoLaTeX utilise le fichier .ist par défaut (dans la distribution AutoLaTeX);

=item F<@detect> - AutoLaTeX essayera de trouver un fichier .ist dans le répertoire du document. Si aucun fichier est trouvé, AutoLaTeX ne passera aucun style à MakeIndex;

=item F<@none> - AutoLaTeX considère qu'aucun fichier ne doit être donné à MakeIndex;

=item F<E<lt>emptyE<gt>> - AutoLaTeX considère qu'aucun fichier ne doit être donné à MakeIndex.

=back

Si la liste contient plus d'une valeur, AutoLaTeX exécutera les comportements correspondants successivement.

=item I<translator include path> : spécifie d'autres répertoires à partir desquels des convertisseurs peuvent être trouvé. Il s'agit d'une liste de chemins séparés par des virgules ou le séparateur de chemin de votre système d'exploitation (S<:> sur Unix, S<;> sur Windows). Si un chemin d'accès contient un caractère ',', vous devez le placer entre guillemets.

=item I<latex_cmd> : ligne de commande de l'outils 'latex'. Valeurs acceptées : toute ligne de commande.

=item I<bibtex_cmd> : ligne de commande de l'outils 'bibtex'. Valeurs acceptées : toute ligne de commande.

=item I<biber_cmd> : ligne de commande de l'outils 'biber'. Valeurs acceptées : toute ligne de commande.

=item I<makeindex_cmd> : ligne de commande de l'outils 'makeindex'. Valeurs acceptées : toute ligne de commande.

=item I<dvi2ps_cmd> : ligne de commande de l'outils 'dvips'. Valeurs acceptées : toute ligne de commande.

=item I<latex_flags> : options de la ligne de commande de l'outils 'latex'. Valeurs acceptées : toute ligne de commande.

=item I<bibtex_flags> : options de la ligne de commande de l'outils 'bibtex'. Valeurs acceptées : toute ligne de commande.

=item I<biber_flags> : options de la ligne de commande de l'outils 'biber'. Valeurs acceptées : toute ligne de commande.

=item I<makeindex_flags> : options de la ligne de commande de l'outils 'makeindex'. Valeurs acceptées : toute ligne de commande.

=item I<dvi2ps_flags> : options de la ligne de commande de l'outils 'dvi2ps'. Valeurs acceptées : toute ligne de commande.

=back

=head3 Section [Clean]

Cette section permet de configurer les fonctionnalités de nettoyage de AutoLaTeX (actions
S<clean> et S<cleanall>).
Les directives reconnues sont :

=over 4

=item I<files to clean> : liste de fichiers à supprimer lorsque l'action S<clean> est invoquée. Les caractères joker du shell sont acceptés.

=item I<files to desintegrate> : iste de fichiers à supprimer lorsque l'action S<cleanall> est invoquée. Les caractères joker du shell sont acceptés.

=back

=head3 Section [Scm]

Cette section permet de configurer les fonctionnalités liées à un SCM (CVS, SVN or others).
Les directives reconnues sont :

=over 4

=item I<scm commit> : ligne de commande pour déposer les modifications sur le SCM.

=item I<scm update> : ligne de commande pour récupérer les changements depuis le SCM.

=back

=head3 Section dédiée à un convertisseur

Une section dédiée à un convertisseur a le même nom que le convertisseur qu'il configure.
Les directives reconnues sont :

=over 4

=item I<include module> : Active ou désactive le convertisseur. Valeurs acceptées : F<yes> or F<no>.

=item I<files to convert> : liste de fichiers que le convertisseur doit prendre en charge, même si l'algorithme d'affectation de AutoLaTeX n'a pas choisi ce convertisseur. Les fichiers sont séparés par le caractère séparateur de chemin de votre système d'exploitation (':' sur Unix, ';' sur Windows).

=back

=head1 INTERFACE UTILISATEUR GRAPHIQUE

Une interface utilisateur graphique est disponible depuis la version 5.0 pour configurer et lancer AutoLaTeX.

The interfaces utilisateur disponibles sont :

=over 4

=item B<Gedit 3:>

C'est l'interface I<officielle> et "à jour" de AutoLaTeX. Un greffon pour l'éditeur léger Gedit 3 <https://projects.gnome.org/gedit> est fourni. Vous pouvez lancer AutoLaTeX et le configurer grâce aux differents panneaux fournis.

=item B<Application Gtk 3:>

Application Gtk 3 permettant de configurer AutoLaTeX. Elle utilise les mêmes fenêtres que le greffon Gedit 3. En effet, ces deux applications utilisent la même bibliothèque Gtk 3 pour AutoLaTeX.

=item B<Sublime Text avec LaTeXTools:>

Depuis 2014, AutoLaTeX est intégré comme l'un des compilateurs du greffon LaTeXTools <https://github.com/SublimeText/LaTeXTools> de Sublime Text. Vous pouvez lancer AutoLaTeX grâce aux outils de construction/compilation de Sublime Text. Jusqu'à présent, il n'est pas encore possible de configurer AutoLaTeX à travers Sublime Text.

=item B<Kile:>

Il n'y a pas de greffon particulier pour Kile. Pour utiliser AutoLaTeX dans cet éditeur, vous devez ajouter un outil de compilation dans la boîte de dialogue "Configure Kile", ou dans le fichier de configuration F<kilerc> dans le dossier de de configuration de KDE (habituellement : C<$HOME/.kde/share/config/kilerc>).
Nous recommandons d'utiliser la configuration ci-dessous pour lancer AutoLaTeX dans Kile (copie du fichier F<kilerc>) :

 ...
 [Tool/AutoLaTeX/Default]
 class=Compile
 close=no
 command=autolatex
 menu=Compile
 options=-v --synctex --noview --search-project-from '%source' all
 state=Editor
 type=Process
 ...

=item B<TeXmaker:>

Il n'y a pas de greffon particulier pour TeXmaker. Pour utiliser AutoLaTeX dans cet éditeur, vous devez ajouter un outil de compilation dans la boîte de dialogue "Configure TeXmaker", ou dans le fichier de configuration F<texmaker.ini> dans le dossier de de configuration de TeXmaker (habituellement : C<$HOME/.config/xm1/texmaker.ini>).
Nous recommandons d'utiliser la configuration ci-dessous pour lancer AutoLaTeX dans TeXmaker (copie du fichier F<texmaker.ini>) :

 ...
 [texmaker]
 ...
 Tools\Userquick=autolatex -v --synctex --noview --search-project-from %.tex
 ...

=item B<TeXworks:>

Il n'y a pas de greffon particulier pour TeXworks. Pour utiliser AutoLaTeX dans cet éditeur, vous devez ajouter un outil de composition dans la boîte de dialogue "Préférences", ou dans le fichier de configuration F<tools.ini> dans le dossier de TeXworks (habituellement : C<$HOME/.TeXworks/configuration/tools.ini>).
Nous recommandons d'utiliser la configuration ci-dessous pour lancer AutoLaTeX dans TeXworks (copie du fichier F<tools.ini>) :

 ...
 [012]
 name=AutoLaTeX
 program=autolatex
 arguments=-v, --synctex, --noview, --search-project-from, $fullname, all
 showPdf=true
 ...

=back

Les interfaces suivantes sont toujours fournies, mais elles sont considérées comme obsolètes :

=over 4

=item B<Gedit 2:>

Un greffon pour l'éditeur Gedit 2 <https://projects.gnome.org/gedit>.

=item B<Sublime Text 2:>

Un greffon pour l'éditeur Sublime Text 2 <http://www.sublimetext.com/2>.

=item B<Application Gtk 2>:

Un ensemble de fenêtres de configuration écrite en Perl et basée sur Gtk 3.

=back

=head1 RAPPORT DE BUG ET COMMENTAIRES

Pour déposer un rapport de bug, un commentaire, ou suggérer une fonctionnalité, vous pouvez (dans l'ordre de préférence) :
a) visiter le site des développeurs sur GitHub <https://github.com/gallandarakhneorg/autolatex/>,
b) visitet la page principale de AutoLaTeX <http://www.arakhne.org/autolatex/>, ou
c) envoyer un email à l'auteur principal à L<galland@arakhne.org>.

=head1 EXIGENCES DU SYSTÈME

AutoLaTeX peut être directement utilisé à partir de n'importe quel répertoire où il n'est pas compressé. Mais vous pouvez compiler et installer les fichiers supplémentaires (manual, ...)

Pour configurer et installer AutoLaTeX, vous pourriez avoir besoin de GNU make.

Vous devez installer les paquets Perl Compress::Zlib pour compiler et installer AutoLaTeX. Ce paquet n'est pas nécessaire pour l'exécution de AutoLaTeX. En outre, pour compiler AutoLaTeX, vous devez installer la commande 'msgfmt' qui fait partie de la bibliothèque 'gettext'.

Pour utiliser AutoLaTeX, vous aurez besoin:

=over 4

=item latex. Le développement de AutoLaTeX a été réalisée en utilisant le distribution TeX Live.

=item Perl version 5.004 ou plus.

=item Plusieurs paquets Perl généralement installés dans votre distribution Perl: Config::Simple, Locale::gettext, Spec::File, ...

=back

=head1 INSTALLATION

L'installation de AutoLaTeX consiste à lancer le script Makefile.PL pour générer un Makefile qui permet de compiler et d'installer AutoLaTeX. Les commandes de base sont les suivants:

F<cd path_to_autoloader_sources/>

F<perl ./Makefile.PL --prefix=/usr>

F<make>

F<make install>

F<make clean>


Le fichier C<INSTALL> donne plus de détails sur l'installation, et il fournit d'autres façons de compiler/installer AutoLaTeX.

=head1 LICENCE AUTOLATEX

S<GNU Public License (GPL)>

Copyright (c) 1998-2014  Stephane GALLAND <galland@arakhne.org>

This program is free software; you can redistribute it and/or modify it under the terms of the GNU L<General Public License|http://www.gnu.org/copyleft/gpl.html> as published by the L<Free Software Foundation|http://www.fsf.org/>; either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program; see the file S<COPYING>. If not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

=head1 COPYRIGHT DU MANUEL

S<GNU Free Documentation License (FDL)>

Copyright (c)  1998-2014  Stephane Galland E<lt>galland@arakhne.orgE<gt>.

Permission is granted to copy, distribute and/or modify this document under the terms of the L<GNU Free Documentation License|http://www.gnu.org/licenses/fdl.txt>, Version 1.2 or any later version published by the L<Free Software Foundation|http://www.fsf.org/>; with the Invariant Sections being S<AUTOLATEX LICENSE> and S<MANUAL COPYRIGHT>, no Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included in the file name S<GNU Free Documentation License.txt>.

=head1 VOIR AUSSI

L<pdflatex>, L<latex>, L<bibtex>, L<biber>, L<epstopdf>,
L<fig2dev>, L<gnuplot>, L<inkscape>, L<umbrello>, L<zcat>, L<texify>
